name: Feature request
description: Suggest an idea for the SDK
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: What problem does this solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: Describe the API/behavior
